pull_requests:
  do_not_increment_build_number: false
image: Visual Studio 2019
configuration:
  - Release RedM
  - Release FiveM
before_build:
  - nuget restore
build:
  parallel: false
  project: MenuAPI.sln
  include_nuget_references: true
  verbosity: minimal
after_build:
  - cmd: if %APPVEYOR_REPO_TAG%==true (appveyor SetVariable -Name VERSION_NAME -Value %APPVEYOR_REPO_TAG_NAME%) else (appveyor SetVariable -Name VERSION_NAME -Value dev)
  - cmd: copy "README.md" ".\MenuAPI\bin\README.md"
  - cmd: 7z a MenuAPI-%VERSION_NAME%.zip -r ".\MenuAPI\bin\*"
  - cmd: appveyor PushArtifact MenuAPI-%VERSION_NAME%.zip
deploy:
  - provider: GitHub
    release: "[Release] MenuAPI $(VERSION_NAME)"
    tag: $(VERSION_NAME)
    artifact: MenuAPI-$(VERSION_NAME).zip
    draft: false
    prerelease: false
    auth_token: $(github_auth)
    on:
      APPVEYOR_REPO_TAG: true
    description: "MenuAPI release, version $(VERSION_NAME). For info check the [docs](https://docs.vespura.com/mapi) or checkout the recent commits on GitHub (the latter is your best bet if you want updated info about this version)."
after_deploy:
  - cmd: curl -H "Content-Type:application/json" -X POST -d "{\"content\":\"^<^@^&540562517806809109^> A new version (**%VERSION_NAME%**) of **%APPVEYOR_PROJECT_NAME%** is now available! :tada:\nAppveyor build:\n**%APPVEYOR_URL%/project/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%/builds/%APPVEYOR_BUILD_ID%** \nGitHub release:\n**https://github.com/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_NAME%/releases/** \"}" %WEBHOOK_URL_TMP%
  - cmd: if %APPVEYOR_REPO_TAG% == True (curl -F "file=@MenuAPI-%VERSION_NAME%.zip" %WEBHOOK_URL_TMP%)
on_success:
  - cmd: curl -H "Content-Type:application/json" -X POST -d "{\"content\":\"âœ… Successfully built **%APPVEYOR_PROJECT_NAME%** (**%VERSION_NAME%**)!\nAppVeyor build url:\n**%APPVEYOR_URL%/project/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%/builds/%APPVEYOR_BUILD_ID%** \nGitHub:\n**https://github.com/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_NAME%/** \"}" %WEBHOOK_URL_TMP%
  - cmd: if %APPVEYOR_REPO_TAG% == True (curl -F "file=@MenuAPI-%VERSION_NAME%.zip" %WEBHOOK_URL_TMP%)
on_failure:
  - cmd: curl -H "Content-Type:application/json" -X POST -d "{\"content\":\"ðŸ’” ðŸ˜¢ Failed to build **%APPVEYOR_PROJECT_NAME%** (**%VERSION_NAME%**)!\nAppVeyor build url:\n**%APPVEYOR_URL%/project/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%/builds/%APPVEYOR_BUILD_ID%** \nGitHub:\n**https://github.com/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_NAME%/** \"}" %WEBHOOK_URL_TMP%